apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wafi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hakeemog/wafi_project.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: wafi-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
